info:
  name: The Zuul API Gateway
  description: API Gateway for the Micro-services  
  version: 1.0.0

zuul:
  routes:
    demo1:
      serviceId: demo1
      path: /api/demo1/**
    demo2:
      serviceId: demo2
      path: /api/demo2/**

spring:
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*|.+favicon.*)

server:
  port: 8765
